#!/usr/bin/python

# written by sundruid

import subprocess

blockCount = subprocess.check_output("bitcoin-cli -conf=/bitcoin_data/.bitcoin/bitcoin.conf getblockcount", shell=True)
blockChain = subprocess.check_output("curl --silent https://blockchain.info/q/getblockcount", shell=True)

blockChain = int(blockChain)
blockCount = int (blockCount)

blockDiff= blockChain - blockCount

print blockCount, ' of ', blockChain, 'completed - ', blockDiff, ' to go'
